netgrif/application-engine

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/pr-build.yml
pom.xml

GitHub workflow

---

pom.xml
src/main/java/com/netgrif/application/engine/importer/service/Importer.java

---
For starters, congratulation on opening a PR of your work. I hope you're proud of your work and yourself :wink: .
There are some things you need to do before this PR is submitted, so read carefully.
First, **set yourself as an assignee**. You can also add other people responsible for code in this PR (i.e. your team lead).
Then **set reviewers**. There should be at least two reviewers. You can set your team lead, projects owner, or senior developer
(after his or her agreement, of course) as a PR reviewer.
The last element on the right panel are labels. Labels should be based on what type of change the PR brings to the table.
You can **add one or more labels** that apply to the PR:
- _Bugfix_ (a change that fixes a bug)
- _New feature_ (a change that introduces new functionality)
- …

Nae 1573 - GET event is initialized with SET type

---

src/main/java/com/netgrif/application/engine/importer/service/Importer.java

- fix initialization of GET event

[NAE-1573] - GET event is initialized with SET type

---

src/main/java/com/netgrif/application/engine/workflow/service/DataService.java

- edit enumeration
Fixes [NAE-1557]
- 
- Linux
- Java 11 
[NAE-1557]: https://netgrif.atlassian.net/browse/NAE-1557?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1557]  Cannot clear optional enumeration

---

src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy

[NAE-1578] change createSetDataEventOutcome to protected
- Fixes [NAE-1578]
- There are no dependencies on other PR
- No need for tests
- No need for tests
[NAE-1578]: https://netgrif.atlassian.net/browse/NAE-1578?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1578] Make createSetDataEventOutcome protected

---

src/main/java/com/netgrif/application/engine/petrinet/service/PetriNetService.java

Fixes [NAE-1582]
- add group into user.nextGroups after invitation
Manual tested on demo app
Manual tested on demo app
[NAE-1582]: https://netgrif.atlassian.net/browse/NAE-1582?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1582] Group is not added into User.nextGroups when invited

---

src/main/java/com/netgrif/application/engine/petrinet/domain/DataGroup.java
src/main/java/com/netgrif/application/engine/workflow/service/DataService.java
src/main/java/com/netgrif/application/engine/workflow/web/responsebodies/DataGroup.java
src/main/java/com/netgrif/application/engine/workflow/web/responsebodies/DataGroupsResource.java
src/main/java/com/netgrif/application/engine/workflow/web/responsebodies/eventoutcomes/LocalisedGetDataGroupsEventOutcome.java

Fixes issue when a field's behaviour is changed in task reference and this change did not apply. It is fixed via requesting reload on the referenced task.
Fixes: [NAE-1577]
No new dependencies was used, imported or implemented.
No new third party dependencies was used, imported or implemented.
Tested it using the provided Petri Net files in Jira issue [NAE-1577]. I imported the Petri Nets into the application engine, and using example app and followed the reproduction steps that where described in Jira issue.
Host OS is macOS Monterey 12.1, the app was running on Angular 10.2.3 with Node 12.22.9 and NPM 6.14.15.
[NAE-1577]: https://netgrif.atlassian.net/browse/NAE-1577?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvb …

[NAE-1577] Task reffed change behavior does not propagate - correction

---

src/main/groovy/com/netgrif/application/engine/startup/DefaultFiltersRunner.groovy

- new properties nae.create.default.filters
- condition of creation
Fixes [NAE-1588]
Manual tested 
Linux Mint 20.3 Cinnamon
Java 11
[NAE-1588]: https://netgrif.atlassian.net/browse/NAE-1588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1588] DefaultFiltersRunner creates new cases every time

---

src/main/java/com/netgrif/application/engine/workflow/service/TaskService.java
src/main/java/com/netgrif/application/engine/workflow/service/interfaces/ITaskService.java
src/main/java/com/netgrif/application/engine/workflow/web/AbstractTaskController.java
src/main/java/com/netgrif/application/engine/workflow/web/PublicTaskController.java
src/main/java/com/netgrif/application/engine/workflow/web/TaskController.java

- change task controller to work with actual task and not the originally taskreffed task, if there is some taskreffed file field
Fixes [NAE-1590]
Manually tested.
Java 11, Mint 20.3
[NAE-1590]: https://netgrif.atlassian.net/browse/NAE-1590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1590] Taskref with file field must be assigned

---

pom.xml
src/main/java/com/netgrif/application/engine/configuration/SwaggerConfiguration.java

Removing SpringFox swagger documentation dependencies for conflicts with other libraries in Spring Boot 2.6.2 .
Currently, there is no valuable fix for the 6.x version of Spring Boot.
Fixes [NAE-1618]
* io.swagger:swagger-core:1.6.5
* io.swagger:swagger-models:1.6.5
Manualy tested
[NAE-1618]: https://netgrif.atlassian.net/browse/NAE-1618?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1618] SpringFox swagger failing in combination with spring actuator

---

src/main/java/com/netgrif/application/engine/importer/service/Importer.java
src/test/groovy/com/netgrif/application/engine/action/ActionTest.groovy
src/test/resources/petriNets/NAE-1616_duplicate_action_id.xml

Fix duplicate call of buildEvents and add test that imports action with id in every possible place. 
Fixes [NAE-1616]
NAE-1616_duplicate_action_id.xml
[NAE-1616]: https://netgrif.atlassian.net/browse/NAE-1616?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1616] - Cannot upload process with action id

---

src/main/java/com/netgrif/application/engine/workflow/service/TaskService.java
src/main/java/com/netgrif/application/engine/workflow/service/WorkflowService.java

- changed to search using List
Implements [NAE-1620]
[NAE-1620]: https://netgrif.atlassian.net/browse/NAE-1620?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1620] Change workflowService findAllById method

---

src/main/java/com/netgrif/application/engine/petrinet/service/PetriNetService.java
src/main/java/com/netgrif/application/engine/workflow/service/TaskService.java
src/main/java/com/netgrif/application/engine/workflow/service/WorkflowService.java

- added logging of user stringId when deleting resources
Implements [NAE-1562]
Manually
| Framework version   |  Spring Boot 2.6.7      |
[NAE-1562]: https://netgrif.atlassian.net/browse/NAE-1562?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1562] Improved logging of deleting resources

---

pom.xml
src/main/java/com/netgrif/application/engine/auth/service/LdapUserDetailsService.java
src/main/java/com/netgrif/application/engine/auth/service/interfaces/ILdapUserRefService.java
src/main/java/com/netgrif/application/engine/configuration/LdapUserServiceConfiguration.java
src/main/java/com/netgrif/application/engine/configuration/authentication/providers/ldap/NetgrifLdapAuthenticationProvider.java
src/main/java/com/netgrif/application/engine/configuration/authentication/providers/ldap/NetgrifLdapAuthenticationProviderLoader.java
src/main/java/com/netgrif/application/engine/configuration/authentication/providers/ldap/UserDetailsContextMapperImpl.java
src/main/java/com/netgrif/application/engine/configuration/ldap/AdLdapConfiguration.java
src/main/java/com/netgrif/application/engine/configuration/ldap/LdapConfiguration.java
src/main/java/com/netgrif/application/engine/configuration/properties/NaeLdapProperties.java
src/main/java/com/netgrif/application/engine/ldap/domain/LdapGroup.java
src/main/java/com/netgrif/application/engine/ldap/domain/LdapGroupRef.java
src/main/java/com/netgrif/application/engine/ldap/domain/LdapLoggedUser.java
src/main/java/com/netgrif/application/engine/ldap/domain/LdapUser.java
src/main/java/com/netgrif/application/engine/ldap/domain/LdapUserRef.java
src/main/java/com/netgrif/application/engine/ldap/domain/repository/LdapGroupRoleRepository.java
src/main/java/com/netgrif/application/engine/ldap/domain/repository/LdapUserRefRepository.java
src/main/java/com/netgrif/application/engine/ldap/domain/repository/LdapUserRepository.java
src/main/java/com/netgrif/application/engine/ldap/service/LdapGroupRefService.java
src/main/java/com/netgrif/application/engine/ldap/service/LdapUserRefService.java
src/main/java/com/netgrif/application/engine/ldap/service/LdapUserService.java
src/main/java/com/netgrif/application/engine/ldap/service/interfaces/ILdapGroupRefService.java
src/main/java/com/netgrif/application/engine/orgstructure/web/LdapController.java
src/main/java/com/netgrif/application/engine/orgstructure/web/responsebodies/LdapGroupResponseBody.java
src/main/java/com/netgrif/application/engine/orgstructure/web/responsebodies/LdapGroupsResource.java

Implements [NAE-1655]
Manually
| Framework version   |  Spring Boot 2.7.0      |
[NAE-1655]: https://netgrif.atlassian.net/browse/NAE-1655?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1655] Better Active Directory compatibility

---

src/main/java/com/netgrif/application/engine/elastic/domain/I18nField.java
src/main/java/com/netgrif/application/engine/elastic/service/ElasticCaseMappingService.java

Implement Elastisearch mapping for I18nField for better filtering for translations.
Implements [NAE-1647]
[NAE-1647]: https://netgrif.atlassian.net/browse/NAE-1647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1647] Elastic mapping for I18N data field

---

src/main/java/com/netgrif/application/engine/ldap/domain/LdapUser.java

Fixes [NAE-1702]
Manually
[NAE-1702]: https://netgrif.atlassian.net/browse/NAE-1702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1702] LdapUser  unique dn

---

src/main/java/com/netgrif/application/engine/workflow/web/AbstractTaskController.java
src/main/java/com/netgrif/application/engine/workflow/web/PublicTaskController.java
src/main/java/com/netgrif/application/engine/workflow/web/TaskController.java

- fix file error propagated
Fixes [NAE-1677]
Manually
[NAE-1677]: https://netgrif.atlassian.net/browse/NAE-1677?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1677] Message from exception thrown in SET event on data field is not propagated in EventOutcome

---

src/main/java/com/netgrif/application/engine/configuration/PrototypesConfiguration.java
src/main/java/com/netgrif/application/engine/pdf/generator/service/PdfDataHelper.java
src/main/java/com/netgrif/application/engine/pdf/generator/service/PdfDrawer.java
src/main/java/com/netgrif/application/engine/pdf/generator/service/PdfGenerator.java

Implement possibility of overriding rendering of fields in PDF form.
Implements [NAE-1646]
| OS                  |   macOS Monterey 12.2.1        |
[NAE-1646]: https://netgrif.atlassian.net/browse/NAE-1646?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1646] Overridable data field render in PDF generator

---

src/main/java/com/netgrif/application/engine/pdf/generator/service/fieldbuilder/TextFieldBuilder.java

- fix number pdf
Fixes [NAE-1720]
manualy
| OS                  |           |
- [x Integration tests
[NAE-1720]: https://netgrif.atlassian.net/browse/NAE-1720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1720] PDF number field is not null

---

src/main/java/com/netgrif/application/engine/elastic/web/requestbodies/CaseSearchRequest.java

- set Deprecated
Fixes [NAE-1714]
Manually
[NAE-1714]: https://netgrif.atlassian.net/browse/NAE-1714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1714] Parameter processIdentifier v classe CaseSearchRequest

---

.github/config.yml
CHANGELOG.md
pom.xml
src/main/java/com/netgrif/application/engine/elastic/web/requestbodies/CaseSearchRequest.java
src/main/java/com/netgrif/application/engine/workflow/web/PublicTaskController.java
src/main/java/com/netgrif/application/engine/workflow/web/TaskController.java

- [NAE-1693] TaskController deleteFile endpoint lacks data about tasks
- [NAE-1714] Parameter processIdentifier in class CaseSearchRequest
[NAE-1693]: https://netgrif.atlassian.net/browse/NAE-1693?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[NAE-1714]: https://netgrif.atlassian.net/browse/NAE-1714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Release 6.2.2

---

src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy

Simplified the way of changing userListField value.
Implements [NAE-1728]
This was tested manually and using unit tests.
[NAE-1728]: https://netgrif.atlassian.net/browse/NAE-1728?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1728] Simplify value for changing user list

---

src/main/java/com/netgrif/application/engine/petrinet/service/PetriNetService.java

- fix
Fixes [NAE-1730]
Manually
[NAE-1730]: https://netgrif.atlassian.net/browse/NAE-1730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1730] PetriNetService cache fix upload bug

---

src/main/groovy/com/netgrif/application/engine/startup/ImportHelper.groovy
src/main/resources/petriNets/engine-processes/org_group.xml

- change deprecated attributes
- change user super to system
Fixes [NAE-1733]
Manually
[NAE-1733]: https://netgrif.atlassian.net/browse/NAE-1733?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1733] Organization group process has deprecated attributes and change import system user

---

src/main/java/com/netgrif/application/engine/auth/domain/LoggedUser.java
src/main/java/com/netgrif/application/engine/configuration/security/PublicAuthenticationFilter.java
src/main/java/com/netgrif/application/engine/configuration/security/jwt/JwtService.java

Fixes [NAE-1777]
Manually
[NAE-1777]: https://netgrif.atlassian.net/browse/NAE-1777?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1777] JWT Token user detail not show password

---

src/main/java/com/netgrif/application/engine/workflow/service/EventService.java
src/test/resources/insurance_portal_demo_test.xml

Fixes [NAE-1773]
Manually
[NAE-1773]: https://netgrif.atlassian.net/browse/NAE-1773?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1773] Action that sets null value to field does not trigger next actions

---

src/main/java/com/netgrif/application/engine/configuration/AbstractSecurityConfiguration.java
src/main/java/com/netgrif/application/engine/configuration/NaeSecurityConfiguration.java
src/main/java/com/netgrif/application/engine/configuration/properties/SecurityConfigProperties.java

Implements [NAE-1780]
Manually
[NAE-1780]: https://netgrif.atlassian.net/browse/NAE-1780?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1780] Configurable CORS security settings

---

src/main/java/com/netgrif/application/engine/pdf/generator/service/fieldbuilder/TextFieldBuilder.java

Implement currency code generation for currency number field in PDF.
Implements [NAE-1753]
This was tested manually generating PDFs.
[NAE-1753]: https://netgrif.atlassian.net/browse/NAE-1753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1753] Currency code in PDF

---

src/main/java/com/netgrif/application/engine/elastic/service/ElasticCaseService.java
src/main/java/com/netgrif/application/engine/elastic/service/ElasticTaskService.java
src/main/java/com/netgrif/application/engine/elastic/service/executors/Executor.java

Implemented catch for Elasticsearch executor exceptions.
Implements [NAE-1776] See also [NAE-1778]
Netgrif Backend PR Config
[NAE-1776]: https://netgrif.atlassian.net/browse/NAE-1776?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[NAE-1778]: …

[NAE-1776] UncaughtExceptionHandler

---

src/main/java/com/netgrif/application/engine/workflow/service/DataService.java
src/test/groovy/com/netgrif/application/engine/workflow/ChangedFieldsAllowedNetsTest.groovy

- set protected
Fixes [NAE-1801]
Manually
[NAE-1801]: https://netgrif.atlassian.net/browse/NAE-1801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1801] Change DataService

---

docs/roles/userlist.md
docs/services/pdf_generator.md
docs/views/public_view.md

Updated documentation.
Implements [NAE-1759]
This was not tested.
[NAE-1759]: https://netgrif.atlassian.net/browse/NAE-1759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1759] Update documentation of public views, PDF generator and user list

---

src/main/java/com/netgrif/application/engine/elastic/service/ElasticCaseService.java

Implemented function in ElasticCaseService to modify PageRequest object.
Fixes [NAE-1812]
| OS                  |   macOS Ventura 13.1     |
[NAE-1812]: https://netgrif.atlassian.net/browse/NAE-1812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1812] Clicking on a column in the case-view that does not have a value has an error behavior

---

src/main/java/com/netgrif/application/engine/ldap/service/LdapGroupRefService.java
src/main/java/com/netgrif/application/engine/ldap/service/interfaces/ILdapGroupRefService.java
src/main/java/com/netgrif/application/engine/petrinet/service/PetriNetService.java

- new method
- implement
Fixes [NAE-1811]
Manually
[NAE-1811]: https://netgrif.atlassian.net/browse/NAE-1811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1811] Process delete does not delete ldap group roles

---

src/main/resources/petriNets/engine-processes/filter.xml
src/main/resources/petriNets/engine-processes/org_group.xml
src/main/resources/petriNets/engine-processes/preference_filter_item.xml
src/test/groovy/com/netgrif/application/engine/insurance/OrsrTest.groovy

Added allowed net field to filter processes.
Implements [NAE-1607]
This was tested manaully.
| OS                  |   macOS Ventura 13.1     |
[NAE-1607]: https://netgrif.atlassian.net/browse/NAE-1607?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1607] Allowed nets configuration for newly created filter

---

src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/UserFieldValue.groovy
src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/UserListFieldValue.groovy
src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
src/main/java/com/netgrif/application/engine/workflow/service/DataService.java

Implemented user list value as set of user values.
Fixes [NAE-1804]
This was tested manually, and with unit tests.
| OS                  |   macOS Ventura 13.1    |
[NAE-1804]: https://netgrif.atlassian.net/browse/NAE-1804?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1804] In UserList field can choose one user multiple times

---

src/main/java/com/netgrif/application/engine/export/domain/ExportDataConfig.java
src/main/java/com/netgrif/application/engine/export/service/ExportService.java
src/main/java/com/netgrif/application/engine/export/service/interfaces/IExportService.java
src/test/resources/petriNets/NAE-1290_Export_actions.xml

Implements [NAE-1834]
[NAE-1834]: https://netgrif.atlassian.net/browse/NAE-1834?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1834] ExportService - Export CSV files in given charset

---

src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
src/main/java/com/netgrif/application/engine/history/service/HistoryService.java
src/main/java/com/netgrif/application/engine/petrinet/service/PetriNetService.java
src/main/java/com/netgrif/application/engine/petrinet/service/interfaces/IPetriNetService.java
src/main/java/com/netgrif/application/engine/workflow/service/DataService.java
src/main/java/com/netgrif/application/engine/workflow/service/TaskService.java
src/main/java/com/netgrif/application/engine/workflow/service/WorkflowService.java
src/main/java/com/netgrif/application/engine/workflow/service/interfaces/IDataService.java
src/test/groovy/com/netgrif/application/engine/auth/TaskAuthorizationServiceTest.groovy
src/test/groovy/com/netgrif/application/engine/auth/WorkflowAuthorizationServiceTest.groovy
src/test/groovy/com/netgrif/application/engine/permissions/ElasticSearchViewPermissionTest.groovy
src/test/groovy/com/netgrif/application/engine/permissions/QueryDSLViewPermissionTest.groovy
src/test/groovy/com/netgrif/application/engine/workflow/UserRefsTest.groovy

Improved request response performance on backend.
Implements [NAE-1865]
[NAE-1865]: https://netgrif.atlassian.net/browse/NAE-1865?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1865] Grid rendering performance improvement

---

src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/UserListField.groovy
src/main/groovy/com/netgrif/application/engine/startup/SuperCreator.groovy
src/main/java/com/netgrif/application/engine/importer/service/FieldFactory.java
src/main/java/com/netgrif/application/engine/workflow/domain/Case.java
src/main/java/com/netgrif/application/engine/workflow/web/responsebodies/LocalisedFieldFactory.java
src/main/java/com/netgrif/application/engine/workflow/web/responsebodies/LocalisedUserListField.java

Added roles attribute to user list field.
Implements [NAE-1874]
[NAE-1874]: https://netgrif.atlassian.net/browse/NAE-1874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1874] Filtering users based on roles when selecting users for UserListField

---

pom.xml
src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
src/main/java/com/netgrif/application/engine/elastic/service/ElasticCaseMappingService.java
src/main/java/com/netgrif/application/engine/importer/service/FieldFactory.java
src/main/java/com/netgrif/application/engine/workflow/domain/menu/MenuItemBody.java
src/main/java/com/netgrif/application/engine/workflow/domain/menu/MenuItemConstants.java
src/main/java/com/netgrif/application/engine/workflow/service/WorkflowService.java
src/main/resources/petriNets/engine-processes/preference_item.xml
src/test/groovy/com/netgrif/application/engine/action/MenuItemApiTest.groovy
src/test/resources/petriNets/filter_api_test.xml

Menu item improvements, that are implemented in NAE-1906
Implements [NAE-1908]
Unit tests and manually
| OS                  |  Linux Mint 21.1 Cinnamon |
| Runtime             |  Java 11  |
| Dependency Manager  |   Maven 3.8.1  |
| Framework version   |    Spring Boot 2.7.8  |
[NAE-1908]: https://netgrif.atlassian.net/browse/NAE-1908?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1 …

[NAE-1908] NAE-1906 Improvements

---

src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/FileFieldValue.groovy
src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/FileListFieldValue.groovy
src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/UserFieldValue.groovy
src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/UserListFieldValue.groovy
src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/CaseChangedFields.groovy
src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/ChangedField.groovy
src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/ChangedFieldContainer.groovy
src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/FrontAction.groovy
src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/Action.groovy
src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/runner/Expression.groovy
src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/validation/Validation.groovy
src/main/groovy/com/netgrif/application/engine/validation/models/AbstractFieldValidation.groovy
src/main/java/com/netgrif/application/engine/auth/domain/AbstractUser.java
src/main/java/com/netgrif/application/engine/auth/domain/Author.java
src/main/java/com/netgrif/application/engine/petrinet/domain/Component.java
src/main/java/com/netgrif/application/engine/petrinet/domain/DataFieldLogic.java
src/main/java/com/netgrif/application/engine/petrinet/domain/Format.java
src/main/java/com/netgrif/application/engine/petrinet/domain/I18nString.java
src/main/java/com/netgrif/application/engine/petrinet/domain/Imported.java
src/main/java/com/netgrif/application/engine/petrinet/domain/Position.java
src/main/java/com/netgrif/application/engine/petrinet/domain/arcs/reference/Reference.java
src/main/java/com/netgrif/application/engine/petrinet/domain/layout/Layout.java
src/main/java/com/netgrif/application/engine/petrinet/domain/version/Version.java
src/main/java/com/netgrif/application/engine/workflow/domain/Case.java
src/main/java/com/netgrif/application/engine/workflow/domain/DataField.java
src/main/java/com/netgrif/application/engine/workflow/domain/Task.java
src/main/java/com/netgrif/application/engine/workflow/domain/TaskPair.java
src/main/java/com/netgrif/application/engine/workflow/domain/eventoutcomes/EventOutcome.java

Add implementation of interface Serializable for core objects
Implements [NAE-1916]
Unit tests
| OS                  |  Linux Mint 21.1 Cinnamon |
| Runtime             |  Java 11  |
| Dependency Manager  |   Maven 3.8.1  |
| Framework version   |    Spring Boot 2.7.8  |
[NAE-1916]: https://netgrif.atlassian.net/browse/NAE-1916?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1916] Serializable core objects

---

src/main/java/com/netgrif/application/engine/elastic/domain/ElasticCase.java
src/main/java/com/netgrif/application/engine/elastic/domain/ElasticTask.java
src/main/java/com/netgrif/application/engine/elastic/service/ElasticCaseService.java
src/main/java/com/netgrif/application/engine/elastic/service/ElasticTaskService.java
src/main/java/com/netgrif/application/engine/elastic/web/requestbodies/CaseSearchRequest.java
src/main/java/com/netgrif/application/engine/importer/service/Importer.java
src/main/java/com/netgrif/application/engine/petrinet/domain/PetriNet.java
src/main/java/com/netgrif/application/engine/petrinet/domain/Transition.java
src/main/java/com/netgrif/application/engine/workflow/domain/Case.java
src/main/java/com/netgrif/application/engine/workflow/domain/Task.java
src/main/java/com/netgrif/application/engine/workflow/service/CaseSearchService.java
src/main/java/com/netgrif/application/engine/workflow/service/TaskSearchService.java
src/main/java/com/netgrif/application/engine/workflow/service/TaskService.java
src/main/java/com/netgrif/application/engine/workflow/web/requestbodies/TaskSearchRequest.java
src/main/java/com/netgrif/application/engine/workflow/web/responsebodies/Task.java

- add tags to petriNet, Case and Task and its request and search bodies
<Implements [NAE-1918]>
none
<No new dependencies were introduced>
manually
| OS                  |     LinuxMint      |
| Runtime             |    JVM       |
[NAE-1918]: https://netgrif.atlassian.net/browse/NAE-1918?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1918] - Tags on process resources

---

src/main/java/com/netgrif/application/engine/history/domain/caseevents/CaseEventLog.java
src/main/java/com/netgrif/application/engine/history/domain/caseevents/CreateCaseEventLog.java

Fixes [NAE-1910]
[NAE-1910]: https://netgrif.atlassian.net/browse/NAE-1910?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1910] Event log is missing change in case's active places

---

src/main/java/com/netgrif/application/engine/configuration/SessionConfiguration.java

- add username and password
Implements [NAE-1932]
| OS                  |   macOS Sonoma 14.2    |
[NAE-1932]: https://netgrif.atlassian.net/browse/NAE-1932?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1932] Enhancement of Redis Connector to Support Authentication

---

src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/FieldType.groovy
src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/StringCollectionField.groovy
src/main/java/com/netgrif/application/engine/importer/service/FieldFactory.java
src/main/java/com/netgrif/application/engine/workflow/service/DataService.java

- implement new type of datafield StringCollection
Implements [NAE-1929]
none
none
manually
| OS                  |     Linux Mint 20      |
[NAE-1929]: https://netgrif.atlassian.net/browse/NAE-1929?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1929] Data field type list of strings

---

pom.xml

- remove dependency
Fixes [NAE-1934]
| OS                  |   macOS Sonoma 14.2    |
[NAE-1934]: https://netgrif.atlassian.net/browse/NAE-1934?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1934] Remove devtools dependency

---

src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/Action.groovy
src/main/java/com/netgrif/application/engine/configuration/ElasticServiceConfiguration.java
src/main/java/com/netgrif/application/engine/configuration/ElasticTaskExecutorConfiguration.java
src/main/java/com/netgrif/application/engine/configuration/properties/ElasticTaskExecutorProperties.java
src/main/java/com/netgrif/application/engine/elastic/domain/ElasticJob.java
src/main/java/com/netgrif/application/engine/elastic/domain/ElasticTaskJob.java
src/main/java/com/netgrif/application/engine/elastic/domain/ElasticTaskRepository.java
src/main/java/com/netgrif/application/engine/elastic/service/ElasticTaskQueueManager.java
src/main/java/com/netgrif/application/engine/elastic/service/ElasticTaskService.java
src/main/java/com/netgrif/application/engine/elastic/service/interfaces/IElasticTaskService.java
src/main/java/com/netgrif/application/engine/petrinet/web/PetriNetController.java
src/test/groovy/com/netgrif/application/engine/elastic/ElasticTaskTest.groovy
src/test/groovy/com/netgrif/application/engine/elastic/ReindexTest.groovy

- new ThreadPoolTaskExecutor
Fixes [NAE-1938]
| OS                  |   macOS Sonoma 14.2.1     |
[NAE-1938]: https://netgrif.atlassian.net/browse/NAE-1938?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1938] Slow Indexing of Elastic Tasks

---

src/main/java/com/netgrif/application/engine/workflow/service/CaseSearchService.java

Implements [NAE-1937]
none
manually
| OS                  |      Linux Mint 20     |
| Runtime             |      Java 11     |
| Dependency Manager  |   Maven 3.3.0        |
| Framework version   |   Spring boot 2.7.8        |
[NAE-1937]: https://netgrif.atlassian.net/browse/NAE-1937?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1937]  Fix the problem with empty string in filter

---

src/main/java/com/netgrif/application/engine/workflow/domain/menu/MenuItemBody.java
src/main/java/com/netgrif/application/engine/workflow/domain/menu/MenuItemConstants.java
src/main/resources/petriNets/engine-processes/preference_item.xml

added param to default-case-view and default-tab-view that checks if create case button is shown
Implements [NAE-1936]
- No new dependencies were introduced.
Tested manually
| OS                  |      Windows 11     |
| Runtime             |      Java 11     |
| Dependency Manager  |      Maven 3.3.0     |
| Framework version   |     Spring boot 2.7.8      |
[NAE-1936]: https://netgrif.atlassian.net/browse/NAE-1936?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1936] Disable create case button using menu items

---

src/main/java/com/netgrif/application/engine/elastic/service/ElasticCaseMappingService.java

add null check
Fixes [NAE-1959]
none
manually
| OS                  |      Linux Mint 20     |
[NAE-1959]: https://netgrif.atlassian.net/browse/NAE-1959?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1959] Indexing enumerationMap field fails when no options exist

---

src/main/java/com/netgrif/application/engine/workflow/service/DataService.java

- fix the bug with normal enum
Fixes [NAE-1960]
none
manually
| OS                  |     Linux Mint 20      |
[NAE-1960]: https://netgrif.atlassian.net/browse/NAE-1960?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1960] Enumeration Map does not propagate changes when selecting

---

src/main/java/com/netgrif/application/engine/configuration/properties/ElasticsearchProperties.java
src/main/java/com/netgrif/application/engine/elastic/service/ElasticCaseService.java
src/main/java/com/netgrif/application/engine/elastic/service/ElasticIndexService.java
src/main/java/com/netgrif/application/engine/elastic/service/interfaces/IElasticIndexService.java
src/main/resources/elastic/default_analyzer.json
src/main/resources/elastic/default_analyzer_ngram.json

- disable date detection
- analyzer
Fixes [NAE-1967]
| OS                  |   macOS Sonoma 14.4.1    |
| Dependency Manager  |  Maven 3.9.6         |
[NAE-1967]: https://netgrif.atlassian.net/browse/NAE-1967?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1967] Elasticsearch disable dynamic field mapping

---

src/main/java/com/netgrif/application/engine/importer/service/FieldFactory.java
src/main/java/com/netgrif/application/engine/importer/service/Importer.java
src/main/java/com/netgrif/application/engine/workflow/domain/Case.java
src/main/java/com/netgrif/application/engine/workflow/domain/DataField.java
src/main/java/com/netgrif/application/engine/workflow/service/DataService.java
src/test/groovy/com/netgrif/application/engine/workflow/DataServiceTest.groovy
src/test/resources/test_setData.xml

- fix the problem with changing properties in net
- add to case component and populated components from datarefs
Fixes [NAE-1958]
none
- manually
| OS                  |    Linux Mint 20       |
[NAE-1958]: https://netgrif.atlassian.net/browse/NAE-1958?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1958] Make component properties changeable

---

pom.xml

Fixes [NAE-1979]
- update org.apache.maven.plugins
- org.apache.maven.plugins
| OS                  |   macOS Ventura 14.5    |
[NAE-1979]: https://netgrif.atlassian.net/browse/NAE-1979?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1979] Optimize Maven Resources Plugin Configuration for Correct File Filtering and Copying

---

src/main/java/com/netgrif/application/engine/workflow/web/PublicTaskController.java

- fix problem with public file list deleting
Fixes [NAE-1983]
none
manually
| OS                  |     Linux Mint 20      |
| Runtime             |     Java 11      |
| Dependency Manager  |      Maven 3.8.4     |
| Framework version   |     SpringBoot 2.6.2      |
[NAE-1983]: https://netgrif.atlassian.net/browse/NAE-1983?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1983] Public view file handling

---

pom.xml

Fixing vulnerabilities.
Implements [NAE-2007]
No dependencies were introduced.
No dependencies were introduced.
This is tested with automatic Snyk test.
| OS                  |   macOS Ventura 14.0     |
[NAE-2007]: https://netgrif.atlassian.net/browse/NAE-2007?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-2007] Vulnerabilities fix

---

CHANGELOG.md
src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/FileFieldValue.groovy
src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/MinIoStorage.groovy
src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/Storage.groovy
src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/StorageField.groovy
src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/StorageType.groovy
src/main/java/com/netgrif/application/engine/elastic/service/ElasticCaseService.java
src/main/java/com/netgrif/application/engine/files/IStorageResolverService.java
src/main/java/com/netgrif/application/engine/files/StorageResolverService.java
src/main/java/com/netgrif/application/engine/files/interfaces/IStorageService.java
src/main/java/com/netgrif/application/engine/files/local/LocalStorageService.java
src/main/java/com/netgrif/application/engine/files/minio/MinIoProperties.java
src/main/java/com/netgrif/application/engine/files/minio/MinIoStorageService.java
src/main/java/com/netgrif/application/engine/importer/service/FieldFactory.java
src/main/java/com/netgrif/application/engine/petrinet/domain/dataset/factory/StorageFactory.java
src/main/resources/application.properties

Implements [NAE-1946]
| OS                  |   macOS Sequoia 15.0     |
| Dependency Manager  |  Maven 3.9.9n         |
| Framework version   |  Spring Boot 2.7.17        |
[NAE-1946]: https://netgrif.atlassian.net/browse/NAE-1946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1946] Remote file connector to S3

---

src/main/groovy/com/netgrif/application/engine/startup/ImportHelper.groovy
src/main/java/com/netgrif/application/engine/auth/service/AbstractUserService.java
src/main/java/com/netgrif/application/engine/elastic/service/ElasticIndexService.java
src/main/java/com/netgrif/application/engine/elastic/service/interfaces/IElasticIndexService.java
src/main/java/com/netgrif/application/engine/ldap/domain/LdapUserRef.java

Fix for several minor bugs.
Fixes [NAE-2024]
| OS                  |   macOS Sequoia 15.0     |
| Dependency Manager  |  Maven 3.9.9n         |
| Framework version   |  Spring Boot 2.7.17        |
[NAE-2024]: https://netgrif.atlassian.net/browse/NAE-2024?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-2024] Collective bug fix

---

src/main/java/com/netgrif/application/engine/workflow/domain/menu/MenuItemBody.java
src/main/java/com/netgrif/application/engine/workflow/domain/menu/MenuItemConstants.java
src/main/resources/petriNets/engine-processes/preference_item.xml

Implemented possibility to mark menu item, that should be automatically opened on the frontend. Menu item can be marked by API or by the UI.
Implements [NAE-2034]
No dependency
Manually and by unit tests
| OS                  |  Ubuntu 24.04.1 LTS |
| Runtime             |  Java 11  |
| Dependency Manager  |   Maven 3.6.3  |
| Framework version   |    Spring Boot 2.7.8  |
[NAE-2034]: https://netgrif.atlassian.net/browse/NAE-2034?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-2034] Open first view

---

src/main/resources/petriNets/engine-processes/dashboard.xml

- add property to component on dashboard
Fixes [NAE-2031]
none
manually
| OS                  |     Linux Mint 22      |
| Runtime             |      Java 11    |
| Dependency Manager  |    Maven 3.9.9n       |
| Framework version   |        Spring Boot 2.7.17   |
[NAE-2031]: https://netgrif.atlassian.net/browse/NAE-2031?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-2031] Dashboard bug fix

---

src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
src/main/groovy/com/netgrif/application/engine/startup/DefaultDashboardRunner.groovy
src/main/groovy/com/netgrif/application/engine/startup/RunnerController.groovy
src/main/java/com/netgrif/application/engine/menu/domain/dashboard/DashboardItemBody.java
src/main/java/com/netgrif/application/engine/menu/domain/dashboard/DashboardItemConstants.java
src/main/java/com/netgrif/application/engine/menu/domain/dashboard/DashboardManagementBody.java
src/main/java/com/netgrif/application/engine/menu/domain/dashboard/DashboardManagementConstants.java
src/main/java/com/netgrif/application/engine/menu/domain/dashboard/DashboardToDataSetOutcome.java
src/main/java/com/netgrif/application/engine/menu/services/DashboardItemServiceImpl.java
src/main/java/com/netgrif/application/engine/menu/services/DashboardManagementServiceImpl.java
src/main/java/com/netgrif/application/engine/menu/services/interfaces/DashboardItemService.java
src/main/java/com/netgrif/application/engine/menu/services/interfaces/DashboardManagementService.java
src/main/resources/petriNets/engine-processes/dashboard_item.xml
src/main/resources/petriNets/engine-processes/menu/menu_item.xml
src/test/resources/dashboard_management_test.xml

Added actions for dashboard management. The developer can create, edit items in the dashboard, and also update the dashboard itself.
Implements [NAE-2063]
It was tested by new dashboard_management_test.xml included in project
| OS                  |    Windows 11       |
| Runtime             |     Oracle OpenJDK 11.0.25     |
| Dependency Manager  |   Maven 3.9.9     |
| Framework version   |     Spring Boot 2.7.18      |
[NAE-2063]: https://netgrif.atlassian.net/browse/NAE-2063?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjU …

[NAE-2063] Action API 6.5.0

---

application-engine/src/main/java/com/netgrif/application/engine/package-info.java
nae-spring-core-adapter/pom.xml
nae-user-common/pom.xml
nae-user-common/src/main/java/com/netgrif/application/engine/auth/package-info.java

- Reorganized QueryDSL dependencies in POM files for better consistency.
- Added new QueryDSL annotation processing configuration in nae-user-common.
- Adjusted package structure and related imports for proper QueryDSL entity mapping.
Rebuilding and running the project and its dependencies.
| OS                  |       Linux (ArchLinux)    |
| Runtime             |        OpenJDK 21   |
| Dependency Manager  |         Maven 3  |
| Framework version   |        Spring boot 3.4.4   |

Refactor QueryDSL dependencies and package structure

---

pom.xml
src/main/java/com/netgrif/application/engine/elastic/service/ElasticCaseService.java
src/main/java/com/netgrif/application/engine/elastic/service/interfaces/IElasticCaseService.java
src/main/java/com/netgrif/application/engine/export/configuration/XlsExportProperties.java
src/main/java/com/netgrif/application/engine/export/domain/CellFactory.java
src/main/java/com/netgrif/application/engine/export/domain/CellType.java
src/main/java/com/netgrif/application/engine/export/domain/ExportedField.java
src/main/java/com/netgrif/application/engine/export/service/XlsExportService.java
src/main/java/com/netgrif/application/engine/export/service/interfaces/IXlsExportService.java
src/main/java/com/netgrif/application/engine/export/utils/XlsExportDateUtils.java
src/main/java/com/netgrif/application/engine/export/web/ExportController.java
src/main/java/com/netgrif/application/engine/export/web/requestbodies/FilteredCasesRequest.java
src/main/java/com/netgrif/application/engine/workflow/domain/menu/MenuItemBody.java
src/main/java/com/netgrif/application/engine/workflow/domain/menu/MenuItemConstants.java
src/main/resources/petriNets/engine-processes/preference_item.xml
src/test/groovy/com/netgrif/application/engine/export/service/XlsExportServiceTest.java

- implement exporting cases from case view
- added ExportController,  XlsExportService, XlsExportConfiguration, XlsExportDateUtils
- added attribute allow export to preference_item and MenuItemBody
- extend IElasticCaseService with existing method to avoid code duplication
- add simple test
Implementation of export cases from case view functionality
Implements [NAE-2100](https://netgrif.atlassian.net/browse/NAE-2100)
Depends on [Components PR](https://github.com/netgrif/components/pull/279)
Mannualy and simple unit test.
- Name of a test [XlsExportServiceTest]()
| OS                  | Fedora |
| Framework …

[NAE-2100] Case view export button as NAE feature
