netgrif/application-engine

src/main/java/com/netgrif/application/engine/workflow/service/FilterImportExportService.java
src/main/java/com/netgrif/application/engine/workflow/service/MenuImportExportService.java
src/main/java/com/netgrif/application/engine/workflow/service/interfaces/IFilterImportExportService.java
src/main/java/com/netgrif/application/engine/workflow/service/interfaces/IMenuImportExportService.java

---
For starters, congratulation on opening a PR of your work. I hope you're proud of your work and yourself :wink: .
There are some things you need to do before this PR is submitted, so read carefully.
First, **set yourself as an assignee**. You can also add other people responsible for code in this PR (i.e. your team lead).
Then **set reviewers**. There should be at least two reviewers. You can set your team lead, projects owner, or senior developer
(after his or her agreement, of course) as a PR reviewer.
The last element on the right panel are labels. Labels should be based on what type of change the PR brings to the table.
You can **add one or more labels** that apply to the PR:
- _Bugfix_ (a change that fixes a bug)
- _New feature_ (a change that introduces new functionality)
- …

Nae 1572 - FilterImportExportService service does not assign import_filter tasks

---

src/main/java/com/netgrif/application/engine/importer/service/Importer.java
src/test/groovy/com/netgrif/application/engine/importer/ImporterTestGroovy.groovy
src/test/resources/this_kw_test.xml

- replaced parseAction function for actions for fields when parsing data events
Fixes [NAE-1559]
- [ImporterTestGroovy.thisKeywordInDataEventsTest](https://github.com/netgrif/application-engine/blob/NAE-1559_2/src/test/groovy/com/netgrif/application/engine/importer/ImporterTestGroovy.groovy#L77)
- Linux
- Java 11
[NAE-1559]: https://netgrif.atlassian.net/browse/NAE-1559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1559] Keyword 'this' in event actions

---

src/main/java/com/netgrif/application/engine/workflow/web/PublicWorkflowController.java

Fixes [NAE-1581]
- implement check for permissions to create case from process in public view
Tested in demo app public view
Tested in demo app public view
[NAE-1581]: https://netgrif.atlassian.net/browse/NAE-1581?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cif …

[NAE-1581] Public view create case permission check

---

src/main/java/com/netgrif/application/engine/orgstructure/groups/NextGroupService.java

Fixes [NAE-1593]
- fix removeUser method to remove group from nextGroups of removed users
Manually tested on demo application
Manually tested on demo application
[NAE-1593]: https://netgrif.atlassian.net/browse/NAE-1593?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1593] Remove user does not remove group from user groups

---

src/main/java/com/netgrif/application/engine/workflow/service/TaskService.java

If there are two transitions in net that are paralel, the second one is executed two times, however there is only one token in its source place.
Fixes [NAE-1600]
This was tested manually using frontend and petri net attached to Jira task.
This was tested on macOS Monterey 12.2.1 using Java 11 and Spring boot 2.6.2
[NAE-1600]: https://netgrif.atlassian.net/browse/NAE-1600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1600] Parallel auto-trigger tasks

---

src/main/java/com/netgrif/application/engine/elastic/service/ElasticCaseService.java

Frontend filter does not work properly when searching for substring. The problem was that Elasticsearch was searching for the substring as a whole word, and not part of substring.
Fixes [NAE-1614]
| OS                  |    macOS Monterey 12.2.1       |
| Runtime             |  Java 11       |
| Dependency Manager  |  Maven 3.8.6        |
| Framework version   |   Spring Boot 2.6.2     |
[NAE-1614]: https://netgrif.atlassian.net/browse/NAE-1614?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1614] Advanced search substring query

---

src/main/java/com/netgrif/application/engine/importer/service/Importer.java
src/test/groovy/com/netgrif/application/engine/petrinet/domain/ImporterTest.groovy
src/test/resources/importTest/NoLabel.xml

Fixes [NAE-1596]
- [ImporterTest.createTransitionNoLabel](https://github.com/netgrif/application-engine/blob/NAE-1596/src/test/groovy/com/netgrif/application/engine/petrinet/domain/ImporterTest.groovy#L236)
[NAE-1596]: https://netgrif.atlassian.net/browse/NAE-1596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1596] Nets with transitions without titles cannot be read

---

src/main/java/com/netgrif/application/engine/workflow/service/DataService.java
src/main/resources/petriNets/engine-processes/filter.xml

Order of data groups created from task reference fields was not correct on grid layout. It was given from the order that is defined in Petri net, but if there is a grid layout, task ref field can have specified Y positions.
Fixes [NAE-1599]
This was tested manually importing agreement.xml petri net and there is a unit test implemented for it.
- testTaskRefOrderOnGridLayout() [DataServiceTest.java](https://github.com/netgrif/application-engine/blob/release/6.0.4/src/test/groovy/com/netgrif/application/engine/workflow/DataServiceTest.groovy)
Netgrif Backend PR Config
| OS                  |   macOS Monterey …

[NAE-1599] Task-reffed fields are not placed in correct position

---

src/main/java/com/netgrif/application/engine/workflow/service/DataService.java
src/test/groovy/com/netgrif/application/engine/workflow/SetDataOnButtonTest.groovy
src/test/resources/button_set_data_test.xml

Updated parseFieldsValues() with button case
Added test Petri net
Added test of functionality
Implements [NAE-1440]
Tested on test Petri net (button_set_data_test.xml) and created test of mentioned Petri net and test using dataService
- [Test Petri net](https://github.com/netgrif/application-engine/blob/NAE-1440/src/test/resources/button_set_data_test.xml)
- [Functionality test](https://github.com/netgrif/application-engine/blob/NAE-1440/src/test/groovy/com/netgrif/application/engine/workflow/SetDataOnButtonTest.groovy)
| OS                  |   Windows 11        |
| Dependency Manager  |  Maven 3.8.4 …

[NAE-1440] setData on button without value

---

src/main/java/com/netgrif/application/engine/workflow/service/DataService.java

Fixes [NAE-1636]
- filter forbidden fields in dataGroup when resolving order on grid
Manually tested in example app
| Runtime             |  Java 11.0.15        |
| Dependency Manager  |  Maven 3.8.1         |
| Framework version   |  Spring Boot 2.6.7        |
[NAE-1636]: https://netgrif.atlassian.net/browse/NAE-1636?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1636] resolveTaskRefOrderOnGrid with forbidden dataField

---

src/main/java/com/netgrif/application/engine/pdf/generator/service/PdfGenerator.java

PDF generator with template did not find the correct template file. The problem was with resolving URI of the file.
Fixes [NAE-1637]
This was tested manually via generating some PDF files with given templates.
| OS                  |   macOS Monterey 12.2.1        |
[NAE-1637]: https://netgrif.atlassian.net/browse/NAE-1637?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHV …

[NAE-1637] PDF generator with template does not work

---

pom.xml

For some PDF documents in file field the preview was not generated.
Fixes [NAE-1652]
New dependencies:
com.twelvemonkeys.imageio
| OS                  |   macOS Monterey 12.2.1        |
[NAE-1652]: https://netgrif.atlassian.net/browse/NAE-1652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1652] For some PDF documents the file preview is not generating

---

src/main/java/com/netgrif/application/engine/pdf/generator/service/PdfGenerator.java

Template file cannot be found when running from jar.
Fixes [NAE-1666]
[NAE-1666]: https://netgrif.atlassian.net/browse/NAE-1666?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1666] PDF Generator template file issue

---

src/main/java/com/netgrif/application/engine/importer/service/Importer.java

If new version of any petri net has any process or case event, these functions were not reloaded in function cache.
Fixes [NAE-1699]
[NAE-1699]: https://netgrif.atlassian.net/browse/NAE-1699?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1699] Create/upload event action is loaded only from the cache

---

src/main/groovy/com/netgrif/application/engine/startup/AnonymousRoleRunner.groovy
src/main/groovy/com/netgrif/application/engine/startup/DefaultRoleRunner.groovy
src/main/groovy/com/netgrif/application/engine/startup/ImportHelper.groovy
src/main/java/com/netgrif/application/engine/auth/service/AbstractUserService.java
src/main/java/com/netgrif/application/engine/importer/service/Importer.java
src/main/java/com/netgrif/application/engine/ldap/service/LdapGroupRefService.java
src/main/java/com/netgrif/application/engine/petrinet/domain/roles/ProcessRoleRepository.java
src/main/java/com/netgrif/application/engine/petrinet/service/ProcessRoleService.java
src/main/java/com/netgrif/application/engine/petrinet/service/interfaces/IProcessRoleService.java
src/test/groovy/com/netgrif/application/engine/action/AssignActionTest.groovy
src/test/groovy/com/netgrif/application/engine/action/RemoveActionTest.groovy
src/test/groovy/com/netgrif/application/engine/auth/TaskAuthorizationServiceTest.groovy
src/test/groovy/com/netgrif/application/engine/petrinet/domain/ActionRefTest.groovy
src/test/groovy/com/netgrif/application/engine/petrinet/domain/EventTest.groovy
src/test/groovy/com/netgrif/application/engine/petrinet/domain/dataset/FieldTest.groovy
src/test/java/com/netgrif/application/engine/petrinet/service/ProcessRoleServiceTest.java
src/test/java/com/netgrif/application/engine/workflow/web/VariableArcsTest.java

Fixes old bug with method ProcessRoleService.findByImportId that returns only one process role even if for that importId several exist. 
There has been added a new method findAllByImport that returns a collection of process roles and the old one is deprecated for backwards compatibility.
Fixes [NAE-1694]
Methods were tested manually and by unit tests.
- [ProcessRoleServiceTest](src/test/java/com/netgrif/application/engine/petrinet/service/ProcessRoleServiceTest.java)
Windows 11, RedHat OpenJDK 11, JUnit 5, Spring Boot tests context.
[NAE-1694]: https://netgrif.atlassian.net/browse/NAE-1694?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1694] ProcessRoleService.findByImportId doesn't return list of process roles

---

src/main/java/com/netgrif/application/engine/workflow/service/DataService.java
src/main/java/com/netgrif/application/engine/workflow/service/interfaces/IDataService.java
src/main/java/com/netgrif/application/engine/workflow/web/AbstractTaskController.java
src/main/java/com/netgrif/application/engine/workflow/web/PublicTaskController.java
src/main/java/com/netgrif/application/engine/workflow/web/TaskController.java
src/test/groovy/com/netgrif/application/engine/workflow/TaskControllerTest.groovy
src/test/resources/petriNets/all_data_refs.xml

When deleting file from file list, set data events were not called.
Fixes [NAE-1626]
This was tested manually and using unit tests.
[NAE-1626]: https://netgrif.atlassian.net/browse/NAE-1626?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1626] Trigger of set event for fileList value deletion is not implemented

---

src/main/java/com/netgrif/application/engine/pdf/generator/service/fieldbuilder/TextFieldBuilder.java

Changed the method to shorten file name in a way
Fixes [NAE-1747]
[NAE-1747]: https://netgrif.atlassian.net/browse/NAE-1747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1747] PDF Generator: incorrect file name shortening

---

src/main/java/com/netgrif/application/engine/pdf/generator/service/fieldbuilder/FieldBuilder.java

Implemented function for breaking long words (URLs, long file names) into multiline text.
Fixes [NAE-1748]
This was tested manually and using unit tests.
[NAE-1748]: https://netgrif.atlassian.net/browse/NAE-1748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1748] Incorrect handling for long lines in PDF generator

---

src/main/java/com/netgrif/application/engine/auth/domain/LoggedUser.java

Added JsonIgnore to LoggedUser.getSelfOrImpersonated
Fixes [NAE-1761]
No new dependencies were introduced..
Tested manually.
[NAE-1761]: https://netgrif.atlassian.net/browse/NAE-1761?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1761] LoggedUser circular dependency

---

src/main/java/com/netgrif/application/engine/petrinet/web/PublicPetriNetController.java

Added URL decoding to public endpoint for PetriNet identifiers to support identifiers in URI other than root.
Implements [NAE-1762]
[NAE-1762]: https://netgrif.atlassian.net/browse/NAE-1762?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1762] Public view URL encoding

---

src/main/java/com/netgrif/application/engine/petrinet/service/PetriNetService.java
src/test/groovy/com/netgrif/application/engine/petrinet/service/CachePetriNetServiceTest.groovy

Fixes [NAE-1755]
Manually
[NAE-1755]: https://netgrif.atlassian.net/browse/NAE-1755?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1755] PetriNetService cache no caching  "null"

---

src/main/groovy/com/netgrif/application/engine/AsyncRunner.groovy
src/main/java/com/netgrif/application/engine/elastic/service/ElasticCaseService.java
src/main/java/com/netgrif/application/engine/elastic/web/requestbodies/CaseSearchRequest.java
src/main/java/com/netgrif/application/engine/pdf/generator/service/fieldbuilder/TextFieldBuilder.java
src/main/java/com/netgrif/application/engine/petrinet/service/interfaces/IPetriNetService.java
src/main/java/com/netgrif/application/engine/petrinet/web/PetriNetController.java
src/main/java/com/netgrif/application/engine/workflow/service/WorkflowService.java
src/main/java/com/netgrif/application/engine/workflow/service/interfaces/IWorkflowService.java

Deletion of PetriNet is now calling delete events of cases.
Fixes [NAE-1756]
This was tested manually, and with unit tests.
[NAE-1756]: https://netgrif.atlassian.net/browse/NAE-1756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1756] Delete PetriNet does not call case delete events

---

src/main/java/com/netgrif/application/engine/auth/domain/AnonymousUser.java
src/main/java/com/netgrif/application/engine/auth/domain/LoggedUser.java

Added default password to anonymous user.
Fixes [NAE-1806]
This was manually tested.
| OS                  |   macOS Ventura 13.0     |
[NAE-1806]: https://netgrif.atlassian.net/browse/NAE-1806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1806] Anonymous user password might not be 'null'

---

src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
src/main/java/com/netgrif/application/engine/workflow/service/DataService.java
src/main/java/com/netgrif/application/engine/workflow/service/TaskService.java
src/main/java/com/netgrif/application/engine/workflow/service/WorkflowService.java
src/main/java/com/netgrif/application/engine/workflow/service/interfaces/IDataService.java
src/test/groovy/com/netgrif/application/engine/action/FilterApiTest.groovy
src/test/groovy/com/netgrif/application/engine/auth/TaskAuthorizationServiceTest.groovy
src/test/groovy/com/netgrif/application/engine/auth/WorkflowAuthorizationServiceTest.groovy
src/test/groovy/com/netgrif/application/engine/permissions/ElasticSearchViewPermissionTest.groovy
src/test/groovy/com/netgrif/application/engine/permissions/QueryDSLViewPermissionTest.groovy
src/test/groovy/com/netgrif/application/engine/workflow/UserRefsTest.groovy

Changed the places of resolution of user references on tasks and cases to only resolve them when case and task is created and when the user list is changed.
Fixes [NAE-1798]
| OS                  |   macOS Ventura 13.0     |
[NAE-1798]: https://netgrif.atlassian.net/browse/NAE-1798?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l …

[NAE-1798] UserRefs resolves everytime when case is saved

---

src/main/java/com/netgrif/application/engine/importer/service/FieldFactory.java

Implemented parsing of options in case of enumeration and multichoice.
Fixes [NAE-1757]
[NAE-1757]: https://netgrif.atlassian.net/browse/NAE-1757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1757] Multichoice and enumeration options not working

---

src/main/java/com/netgrif/application/engine/configuration/ElasticCaseSearchConfiguration.java
src/main/java/com/netgrif/application/engine/configuration/ElasticServiceConfiguration.java
src/main/java/com/netgrif/application/engine/elastic/service/ElasticCasePrioritySearch.java
src/main/java/com/netgrif/application/engine/elastic/service/ElasticCaseService.java
src/main/java/com/netgrif/application/engine/elastic/service/interfaces/IElasticCasePrioritySearch.java
src/main/java/com/netgrif/application/engine/elastic/service/interfaces/IElasticCaseService.java

Implements [NAE-1833]
[NAE-1833]: https://netgrif.atlassian.net/browse/NAE-1833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNv …

[NAE-1833] Configuration priority  search

---

src/main/java/com/netgrif/application/engine/workflow/service/TaskSearchService.java

Added check for empty negativeViewUsers in TaskSearchService.
Fixes [NAE-1831]
[NAE-1831]: https://netgrif.atlassian.net/browse/NAE-1831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1831] Taks with negative permissions displayed

---

src/main/groovy/com/netgrif/application/engine/startup/DemoRunner.groovy
src/main/java/com/netgrif/application/engine/auth/domain/Authority.java
src/main/java/com/netgrif/application/engine/auth/service/AbstractUserService.java
src/main/java/com/netgrif/application/engine/auth/service/UserService.java
src/main/java/com/netgrif/application/engine/auth/service/interfaces/IUserService.java

- fix NullPointerException on adding a user to authority property users
- return saved user entity after assigning it new authority
Fixes [NAE-1860]
Tested manually by performing request POST `localhost:8080/api/user/{id of super user}/authority/assign` and then check the change in the database.
| OS                  |      Windows 11     |
| Runtime             |          Java 11 (RedHat OpenJDK) |
| Dependency Manager  |        Maven 3   |
| Framework version   |        Spring boot 2.7.8   |
[NAE-1860]: https://netgrif.atlassian.net/browse/NAE-1860?atlOrigin=eyJpIjoiNWRkNT …

[NAE-1860] Assigning authority to a user via REST API ends up with error

---

src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/FieldActionsRunner.groovy
src/test/groovy/com/netgrif/application/engine/petrinet/domain/FunctionsTest.groovy
src/test/resources/petriNets/function_res_v2.xml
src/test/resources/petriNets/function_test_v2.xml

Fixed problem, where an instance of ActionDelegate couldn't be released off the memory
Fixes [NAE-1875]
Manually and with unit tests. For memory leaks used IntelliJ profiler
| OS                  |  Linux Mint 21.1 Cinnamon |
| Runtime             |  Java 11  |
| Dependency Manager  |   Maven 3.8.1  |
| Framework version   |    Spring Boot 2.7.8  |
[NAE-1875]: https://netgrif.atlassian.net/browse/NAE-1875?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1875] Namespace functions cause memory leak

---

src/main/java/com/netgrif/application/engine/workflow/service/FieldActionsCacheService.java

Fixes [NAE-1836]
- change key actionsCache
| OS                  |   macOS Ventura 13.3.1    |
[NAE-1836]: https://netgrif.atlassian.net/browse/NAE-1836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1836] Actions cache is broken (for multiple versions of the same process)

---

src/main/java/com/netgrif/application/engine/ldap/domain/LdapUser.java

- remove problematic unique setting
removes unique=true designation from Indexed annotation for LdapUser. The reason for this is that users cannot be properly indexed (on property DN) as long as both LdapUser and User classes are saved within the same mongodb collection
Fixes [NAE-1930]
none
none
none
[NAE-1930]: https://netgrif.atlassian.net/browse/NAE-1930?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1930] Modify Annotation in LdapUser Class for Indexing

---

CHANGELOG.md
src/main/java/com/netgrif/application/engine/workflow/service/DataService.java
src/main/java/com/netgrif/application/engine/workflow/service/TaskSearchService.java
src/main/java/com/netgrif/application/engine/workflow/web/requestbodies/TaskSearchRequest.java

Implemented function in DataService to resolve task ref data only when it is needed.
Implements [NAE-1901]
[NAE-1901]: https://netgrif.atlassian.net/browse/NAE-1901?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-1901] Taskref rendering update

---

README.md
src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
src/main/groovy/com/netgrif/application/engine/startup/ImportHelper.groovy
src/main/java/com/netgrif/application/engine/ApplicationEngine.java
src/main/java/com/netgrif/application/engine/auth/service/UserService.java
src/main/java/com/netgrif/application/engine/auth/service/interfaces/IUserService.java
src/main/java/com/netgrif/application/engine/auth/web/PublicUserController.java
src/main/java/com/netgrif/application/engine/auth/web/UserController.java
src/main/java/com/netgrif/application/engine/history/domain/baseevent/EventLog.java
src/main/java/com/netgrif/application/engine/history/domain/caseevents/CaseEventLog.java
src/main/java/com/netgrif/application/engine/history/domain/petrinetevents/DeletePetriNetEventLog.java
src/main/java/com/netgrif/application/engine/history/domain/petrinetevents/ImportPetriNetEventLog.java
src/main/java/com/netgrif/application/engine/history/domain/petrinetevents/PetriNetEventLog.java
src/main/java/com/netgrif/application/engine/importer/service/Importer.java
src/main/java/com/netgrif/application/engine/orgstructure/groups/NextGroupService.java
src/main/java/com/netgrif/application/engine/petrinet/domain/roles/ProcessRole.java
src/main/java/com/netgrif/application/engine/petrinet/domain/roles/ProcessRoleRepository.java
src/main/java/com/netgrif/application/engine/petrinet/service/PetriNetService.java
src/main/java/com/netgrif/application/engine/petrinet/service/ProcessRoleService.java
src/main/java/com/netgrif/application/engine/workflow/domain/Case.java
src/main/java/com/netgrif/application/engine/workflow/domain/ProcessResourceId.java
src/main/java/com/netgrif/application/engine/workflow/domain/Task.java
src/main/java/com/netgrif/application/engine/workflow/domain/repositories/CaseRepository.java
src/main/java/com/netgrif/application/engine/workflow/domain/repositories/TaskRepository.java
src/main/java/com/netgrif/application/engine/workflow/service/CaseSearchService.java
src/main/java/com/netgrif/application/engine/workflow/service/TaskSearchService.java
src/main/java/com/netgrif/application/engine/workflow/service/TaskService.java
src/main/java/com/netgrif/application/engine/workflow/service/WorkflowService.java
src/main/java/com/netgrif/application/engine/workflow/web/responsebodies/Task.java

Implements new id object ProcessResourceId that represents the id of an object that belongs to some process. The id is defined with two parts with the symbol '-' as a separator. The first part, prefix, is encoded Process (PetriNet) ObjectId named process short. The second part is an ObjectId that MongoDB generates and thus it is backwards compatible.
This definition of an id helps to identify to what process an object belongs to quickly. It is helpful in the process-resolving for NAE cluster.
Implements [NAE-1988]
Manually tested and current tests refactored to match new id.
| OS                  |           Windows 11|
| Runtime             |           Java OpenJDK 21|
| …

[NAE-1988] Extend Id of processes resource for better resolution

---

src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/Field.groovy
src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/Storage.groovy
src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/validation/LocalizedValidation.groovy
src/main/java/com/netgrif/application/engine/elastic/web/requestbodies/CaseSearchRequest.java
src/main/java/com/netgrif/application/engine/workflow/web/requestbodies/TaskSearchRequest.java
src/main/java/com/netgrif/application/engine/workflow/web/requestbodies/taskSearch/TaskSearchCaseRequest.java
src/main/java/com/netgrif/application/engine/workflow/web/responsebodies/DataFieldsResource.java
src/main/java/com/netgrif/application/engine/workflow/web/responsebodies/LocalisedField.java

Implements [NAE-2008]
| OS                  |   macOS Sequoia 15.0        |
| Runtime             |  Node 20.17.0         |
| Dependency Manager  |  NPM 10.8.2        |
| Framework version   |  Angular 13.3.1         |
[NAE-2008]: https://netgrif.atlassian.net/browse/NAE-2008?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-2008] Serialisation of classes

---

src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
src/main/java/com/netgrif/application/engine/petrinet/domain/roles/ProcessRoleRepository.java
src/main/java/com/netgrif/application/engine/petrinet/service/ProcessRoleService.java
src/main/java/com/netgrif/application/engine/petrinet/service/interfaces/IProcessRoleService.java
src/main/java/com/netgrif/application/engine/workflow/service/ConfigurableMenuService.java
src/main/java/com/netgrif/application/engine/workflow/service/DataService.java
src/main/java/com/netgrif/application/engine/workflow/service/interfaces/IDataService.java

Implements [NAE-2016]
- <Name of a test [test file](link to the test file)>
| OS                  |  macOS …

[NAE-2016] Global roles for menu items permissions

---

docker-compose.yml
pom.xml
src/main/java/com/netgrif/application/engine/elastic/service/ElasticCaseService.java
src/main/java/com/netgrif/application/engine/elastic/service/ElasticViewPermissionService.java

- ElasticCaseService, ElasticViewPermissionService: refactored queries to use termsQuery and filter, reducing clause count.
- pom.xml: updated spring-session to spring-session-core
more info:
https://www.elastic.co/guide/en/elasticsearch/reference/7.17/query-dsl-term-query.html
https://www.elastic.co/guide/en/elasticsearch/reference/7.17/query-dsl-terms-query.html
Fixes [NAE-2053]
Change dependency from
<dependency>
<groupId>org.springframework.session</groupId>
<artifactId>spring-session</artifactId>
<version>2.0.0.M2</version>
</dependency>
to:
<dependency>
<groupId>org.springframework.session</groupId>
<artifactId>spring-session-core</artifactId>
</dependency>
There are no …

[NAE-2053] Optimize ElasticCaseService queries to eliminate maxClauseCount error

---

src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
src/main/groovy/com/netgrif/application/engine/startup/DashboardManagementRunner.groovy
src/main/groovy/com/netgrif/application/engine/startup/DashboardRunner.groovy
src/main/groovy/com/netgrif/application/engine/startup/FilterRunner.groovy
src/main/groovy/com/netgrif/application/engine/startup/ImpersonationRunner.groovy
src/main/groovy/com/netgrif/application/engine/startup/ImportHelper.groovy
src/main/groovy/com/netgrif/application/engine/startup/RunnerController.groovy
src/main/java/com/netgrif/application/engine/workflow/domain/menu/MenuItemBody.java
src/main/java/com/netgrif/application/engine/workflow/domain/menu/MenuItemConstants.java
src/main/resources/petriNets/engine-processes/dashboard_item.xml
src/main/resources/petriNets/engine-processes/dashboard_management.xml
src/main/resources/petriNets/engine-processes/preference_item.xml

Implements configurable dashboard component. Component is managed by process dashboard_management and displays dashboard items (dashboard_item process) in tile view. 
Configuration available in dashboard:
- add dashboard item
- remove dashboard item
- reorder items
- changes to toolbar
Configuration for dashboard items:
- name of item
- icon of item (material or web icon)
- font/icon color
- font weight
- internal/external item
Implements [NAE-2033]
Depends on #(283)
Manually from application
| OS                  |     Linux Mint 21      |
| Runtime             |      Java 11.0.25      |
| Dependency Manager  |    maven 3.9.9    |
| Framework …

[NAE-2033] Welcome dashboard

---

src/main/java/com/netgrif/application/engine/elastic/service/ElasticPetriNetService.java
src/main/java/com/netgrif/application/engine/elastic/service/interfaces/IElasticPetriNetService.java
src/main/java/com/netgrif/application/engine/petrinet/web/PetriNetController.java

- implement basic elastic search for title and identifier to ElasticPetriNetService and implement endpoint for elastic search
- 
Implements [NAE-2039]
none
manually
| OS                  |     Linux Mint 22      |
| Runtime             |      Java 11.0.25      |
| Dependency Manager  |    maven 3.9.9    |
| Framework version   |    Spring Boot 2.7.18       |
[NAE-2039]: https://netgrif.atlassian.net/browse/NAE-2039?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhM …

[NAE-2039] Search in workflow view 

---

src/main/java/com/netgrif/application/engine/menu/services/MenuItemService.java

Fixes the condition for setting the field hasChildren correctly. Added condition to check if newValue is not empty.
Fixes [NAE-2099]
Manually on an already existing project.
| OS                  | Windows 11  |
| Runtime             |  Oracle OpenJDK 11.0.25   |
| Dependency Manager  |  Maven 3.9.9   |
| Framework version   |   Spring Boot 2.7.18   |
[NAE-2099]: https://netgrif.atlassian.net/browse/NAE-2099?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[NAE-2099] MenuItemService.appendChildCaseIdInDataSet not setting hasChildren correctly

---

application-engine/src/main/java/com/netgrif/application/engine/ApplicationEngine.java
application-engine/src/main/java/com/netgrif/application/engine/configuration/LoadModule.java
application-engine/src/main/java/com/netgrif/application/engine/configuration/LoadedModulesEndpoint.java
application-engine/src/main/java/com/netgrif/application/engine/configuration/properties/CacheProperties.java
application-engine/src/main/resources/application.properties
nae-user-ce/pom.xml

- Add loaded module detection and expose it via Actuator
- Introduced `LoadModule` and `LoadedModulesEndpoint` to detect and expose loaded modules' metadata via a new Actuator endpoint. Updated application properties, caching configuration, and dependencies to support this feature. Enhanced security settings and excluded JDBC auto-configuration to streamline the application setup.
Fixes [NAE-2108]
Depends on https://github.com/netgrif/nae-modul-maven-plugin/pull/1
- <Name of a …

[NAE-2108] Implement actuator for listing registered modules with manifest details
